/*
 * This Java source file was generated by the Gradle 'init' task.
 */
package MTBMS;

import org.junit.Test;

import java.io.ByteArrayInputStream;
import java.io.ByteArrayOutputStream;
import java.io.InputStream;
import java.io.PrintStream;
import java.nio.charset.StandardCharsets;
import java.util.Scanner;

import static org.junit.Assert.*;
import static org.junit.Assert.assertNotNull;

public class BookingSystemTest {

    @Test
    public void testPage(){
        BookingSystem bookingSystem = new BookingSystem();
        bookingSystem.defaultPage();
    }

    @Test
    public void testLogin(){
        BookingSystem bookingSystem = new BookingSystem();
        bookingSystem.login(xx,xxx,);
    }

    @Test
    public void testSignUp(){
        BookingSystem bookingSystem = new BookingSystem();
        bookingSystem.signUp("xxx_id");
    }

    @Test
    public void testLoginOut(){
        BookingSystem bookingSystem = new BookingSystem();
        bookingSystem.logOut();
    }

    @Test
    public void testGretting(){
        BookingSystem bookingSystem = new BookingSystem();
        bookingSystem.getGreeting();
    }


}


